### ISSUE TITLE
Extract Mesh from 3dvnet

### ISSUE THREAD

**Issue by bityigoss** [alexrich021/3dvnet#5]
Thanks for your great work.
I have a question on how to extract mesh from 3dvnet, since the saved file do not contain a mesh.ply file.

thanks.

**Comment by alexrich021** [comment]
Hi, thanks for your interest!

In `mv3d/eval/config.py`, you can set `RUN_TSDF_FUSION = True` and that will run TSDF fusion during evaluation. The only flag that affects the produced TSDFs is `MASK_USING_GT_MESH`. That will toggle masking out regions in the produced mesh for which the GT mesh contains holes due to depth sensor noise.

For the best quality TSDFs for depth-based methods, I would consider filtering the depth maps prior to TSDF fusion using a multi-view consistency check. Our evaluation pipeline as constructed simply runs TSDF fusion without any multi-view consistency check.

Hope this helps!
